#ifndef _NW4R_G3D_
#define _NW4R_G3D_
#include <types.hpp>
#include <core/nw4r/g3d/AnmChr.hpp>
#include <core/nw4r/g3d/AnmClr.hpp>
#include <core/nw4r/g3d/AnmObj.hpp>
#include <core/nw4r/g3d/AnmShp.hpp>
#include <core/nw4r/g3d/AnmTexPat.hpp>
#include <core/nw4r/g3d/AnmTexSrt.hpp>
#include <core/nw4r/g3d/CalcWorld.hpp>
#include <core/nw4r/g3d/Camera.hpp>
#include <core/nw4r/g3d/common.hpp>
#include <core/nw4r/g3d/Fog.hpp>
#include <core/nw4r/g3d/g3dObj.hpp>
#include <core/nw4r/g3d/Light.hpp>
#include <core/nw4r/g3d/res/ResAnmAmbLight.hpp>
#include <core/nw4r/g3d/res/ResAnmCamera.hpp>
#include <core/nw4r/g3d/res/ResAnmChr.hpp>
#include <core/nw4r/g3d/res/ResAnmClr.hpp>
#include <core/nw4r/g3d/res/ResAnmFog.hpp>
#include <core/nw4r/g3d/res/ResAnmLight.hpp>
#include <core/nw4r/g3d/res/ResAnmScn.hpp>
#include <core/nw4r/g3d/res/ResAnmShp.hpp>
#include <core/nw4r/g3d/res/ResAnmTexPat.hpp>
#include <core/nw4r/g3d/res/ResAnmTexSrt.hpp>
#include <core/nw4r/g3d/res/ResCommon.hpp>
#include <core/nw4r/g3d/res/ResDic.hpp>
#include <core/nw4r/g3d/res/ResFile.hpp>
#include <core/nw4r/g3d/res/ResLightSet.hpp>
#include <core/nw4r/g3d/res/ResMat.hpp>
#include <core/nw4r/g3d/res/ResMdl.hpp>
#include <core/nw4r/g3d/res/ResNode.hpp>
#include <core/nw4r/g3d/res/ResTex.hpp>
#include <core/nw4r/g3d/res/ResTexPlttInfo.hpp>
#include <core/nw4r/g3d/res/ResVtx.hpp>
#include <core/nw4r/g3d/ScnMdl.hpp>
#include <core/nw4r/g3d/ScnMdlSimple.hpp>
#include <core/nw4r/g3d/ScnObj.hpp>
#include <core/nw4r/g3d/ScnProc.hpp>
#include <core/nw4r/g3d/ScnRoot.hpp>

#endif