//------------------------------------------------------------------------------
// <auto-
//
//
//
// d>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Pulsar_Pack_Creator {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class PulsarRes {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal PulsarRes() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Pulsar_Pack_Creator.PulsarRes", typeof(PulsarRes).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] BMG100 {
            get {
                object obj = ResourceManager.GetObject("BMG100", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to #BMG
        ///
        ///   7dd	= Wiimmfi
        ///   7de	= Riivolution Channel
        ///   7e8	= Play via Wiimmfi!
        ///   7e9	= Play with a friend via Wiimmfi!
        ///   7ea	= Return to Riivolution!
        ///   7f1	= Wiimmfi (1P)
        ///   7f2	= Wiimmfi (2P)
        ///   818	= You will now disconnect\nfrom Wiimmfi and\nreturn to the main menu.
        ///   841	= \z{602,0} and \z{802,120000}\nwill connect to Wiimmfi\ntogether. Is this OK?
        ///   fa8	= There are no Friends registered\nin your Friend Roster.\n\nRegister Friends to play\ntogether on Wiimmfi.\040
        ///   faa	= Connecting to [rest of string was truncated]&quot;;.
        /// </summary>
        public static string BMG1001 {
            get {
                return ResourceManager.GetString("BMG1001", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] BMG200 {
            get {
                object obj = ResourceManager.GetObject("BMG200", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] CommonAssets {
            get {
                object obj = ResourceManager.GetObject("CommonAssets", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] E {
            get {
                object obj = ResourceManager.GetObject("E", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string Files {
            get {
                return ResourceManager.GetString("Files", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] J {
            get {
                object obj = ResourceManager.GetObject("J", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] K {
            get {
                object obj = ResourceManager.GetObject("K", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] Loader {
            get {
                object obj = ResourceManager.GetObject("Loader", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 800018a8 0x800018a8
        ///80001d50 0x80001d50
        ///80001d6c 0x80001d6c
        ///80001d90 0x80001d90
        ///80001dc0 0x80001dc0
        ///80001de8 0x80001de8
        ///80001dec 0x80001dec
        ///80001e14 0x80001e14
        ///80001e30 0x80001e30
        ///80001f1c 0x80001f1c
        ///80001f40 0x80001f40
        ///80001f54 0x80001f54
        ///80002440 0x80002440
        ///8000245c 0x8000245c
        ///8000249c __TRKreset
        ///80005f34 memcpy
        ///80005f84 __fill_mem
        ///80006038 memset
        ///80006068 __check_pad3
        ///80006090 __set_debug_bba
        ///8000609c __get_debug_bba
        ///800060a4 __start
        ///80006210 __init_registers
        ///800062a0 __init_data
        /// [rest of string was truncated]&quot;;.
        /// </summary>
        public static string MAP {
            get {
                return ResourceManager.GetString("MAP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] P {
            get {
                object obj = ResourceManager.GetObject("P", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [P]
        ///#Base version: MKWii PAL
        ///80000000-*: +0x0
        ///#
        ///[E]
        ///80000000-8000802f: +0x0
        ///8000808c-8000adbb: -0x40
        ///8000af24-8000b6b3: -0xa0
        ///8000b6b4-8000c173: +0x15994
        ///8000c174-80021ba7: -0xb60
        ///80021ba8-80225f1b: -0xa0
        ///802261f8-802402df: -0x384
        ///802402e0-80240e17: +0x3f1c
        ///80240e18-80244dd3: -0xebc
        ///80276054-8027b000: -0x4340
        ///802a3d60-802a407f: -0x4368
        ///802a4080-80386e3f: -0x4380
        ///80386f48-80386f8f: -0x4388
        ///805103b4-80510a8f: -0x4380
        ///80510b84-8052d297: -0x4474
        ///8052d298-8052d96b: +0x22568
        ///8052d96c-8053d97b [rest of string was truncated]&quot;;.
        /// </summary>
        public static string Port {
            get {
                return ResourceManager.GetString("Port", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] RaceAssets {
            get {
                object obj = ResourceManager.GetObject("RaceAssets", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] UIAssets {
            get {
                object obj = ResourceManager.GetObject("UIAssets", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] wbmgt {
            get {
                object obj = ResourceManager.GetObject("wbmgt", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;wiidisc version=&quot;1&quot;&gt;
        ///	&lt;id game=&quot;RMC&quot;/&gt;
        ///	&lt;options&gt;
        ///		&lt;section name=&quot;{$pack}&quot;&gt;
        ///			&lt;option name=&quot;Pack&quot;&gt;
        ///				&lt;choice name=&quot;Enabled&quot;&gt;
        ///					&lt;patch id=&quot;PackLoadPack&quot;/&gt;
        ///				&lt;/choice&gt;
        ///			&lt;/option&gt;
        ///			&lt;option name=&quot;My Stuff&quot;&gt;
        ///				&lt;choice name=&quot;From CTGP-r&quot;&gt;
        ///					&lt;patch id=&quot;CTGPLoad&quot;/&gt;
        ///				&lt;/choice&gt;
        ///				&lt;choice name=&quot;From Pack&quot;&gt;
        ///					&lt;patch id=&quot;PackLoad&quot;/&gt;
        ///				&lt;/choice&gt;
        ///			&lt;/option&gt;
        ///		&lt;/section&gt;
        ///	&lt;/options&gt;	
        ///	&lt;patch id=&quot;PackLoadPack&quot;&gt;
        ///		&lt;memory offset=&quot;0x80242698&quot; value=&quot;4BDC1968&quot; original=&quot;4e8000 [rest of string was truncated]&quot;;.
        /// </summary>
        public static string XML {
            get {
                return ResourceManager.GetString("XML", resourceCulture);
            }
        }
    }
}
